### ISSUE TITLE
Highscores Offline.. desculpa, eu acho..

### ISSUE THREAD

**Issue by GabrielMottaDev** [oprogramadorreal/Destroying-Minecraft#1]
Então.. eu usei um proxy pra interceptar e alterar os valores das requests de pontuação, e ver se conseguia inserir um valor absurdo no highscores..
Eu acho que consegui, até porque o http://dreamlo.com está me retornando como top1 (& top2 hehe ^-^):

![image](https://user-images.githubusercontent.com/29769845/101750646-140c4100-3aae-11eb-8400-34527a6c9a91.png)

Mas acho que acabei bugando a tela que parou de carregar =(

![image](https://user-images.githubusercontent.com/29769845/101729669-5c6c3480-3a97-11eb-88f7-a0606a6e4df1.png)

PS: Sei que corrigir o loading da tela não será tão dificil.. mas será que rende um video tentando fazer um "anticheat"?
PSx2: Desculpa sério.. não queria estragar a brincadeira kk

Edit: Agora que vi que o Drakiz tinha sido mais rápido que eu em burlar o placar ;-; ~mas fui eu que reportei e corrigi e_e~

**Comment by GabrielMottaDev** [comment]
Me senti culpado e fiz um patch: #2 

![image](https://user-images.githubusercontent.com/29769845/101749621-b88d8380-3aac-11eb-993b-f975ef25c055.png)

Pelo oque percebi era um problema de alocação de memoria. A variavel da pontuação se restringe a Int32 (Até 2147483647), quando o codigo tentava dar parse em um valor maior gerava exception, e como não era tratada... ele parava todo o script.

Viu.. tudo funcionando (ou quase) =)

**Comment by oprogramadorreal** [comment]
Muuuuito obrigado, cara! Sensacional! Hahahah. Já aceitei seu pull request! Daqui a pouco subo a versão com o seu patch lá pro itch.io =)
